import random

land = [230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249]
common = [4, 7, 8, 9, 10, 13, 14, 18, 20, 21, 22, 24, 26, 28, 29, 31, 34, 36, 37, 38, 41, 43, 44, 47, 48, 49, 50, 53, 54, 56, 57, 60, 63, 65, 66, 69, 70, 73, 75, 79, 81, 83, 84, 87, 89, 91, 93, 94, 95, 96, 97, 99, 100, 101, 110, 113, 114, 117, 118, 119, 121, 122, 123, 125, 130, 132, 134, 136, 139, 141, 142, 143, 144, 146, 148, 149, 151, 154, 155, 159, 163, 166, 167, 173, 175, 177, 178, 179, 182, 184, 185, 187, 190, 191, 193, 194, 196, 198, 199, 200, 212]
uncommon = [2, 5, 11, 15, 27, 32, 33, 35, 40, 42, 45, 46, 52, 61, 64, 67, 71, 78, 88, 90, 92, 103, 104, 107, 108, 115, 120, 127, 128, 129, 131, 137, 140, 156, 157, 158, 161, 164, 168, 169, 180, 181, 183, 186, 197, 202, 203, 204, 205, 206, 208, 209, 210, 211, 215, 216, 219, 220, 223, 224]
rare = [1, 6, 12, 17, 19, 23, 25, 30, 51, 59, 62, 68, 72, 74, 76, 80, 85, 86, 102, 105, 106, 111, 112, 116, 126, 133, 138, 145, 150, 152, 153, 160, 162, 165, 170, 171, 172, 176, 192, 195, 201, 207, 213, 214, 217, 218, 221, 222, 225, 226, 227, 228, 229]
mythic = [3, 16, 39, 55, 58, 77, 82, 98, 109, 124, 135, 147, 174, 188, 189]

white = range(1,41)
blue = range(41,81)
black = range(81,121)
red = range(121,161)
green = range(161,201)
colorless = range(201,250)
colored = range(1,201)

bomb = [1,6,12,17,51,59,68,72,76,86,105,106,111,116,126,133,138,145,160,162,165,171,172,176,195,201,207,213,217,221,3,16,39,55,58,82,98,109,124,135,147,179,188,189]
removal = 

draft_picks = [None,1.033, 3.817, 1.017, 13.482, 4.392, 1.029, 9.328, 5.479, 8.899, 9.756, 9.194, 1.039, 11.379, 7.004, 8.137, 1.010, 1.052, 2.624, 1.213, 5.561, 7.981, 11.440, 1.752, 12.512, 9.661, 10.869, 1.606, 3.729, 4.064, 7.127, 11.738, 4.033, 1.711, 12.184, 7.603, 11.400, 10.278, 5.924, 1.014, 2.564, 3.529, 6.135, 9.405, 3.965, 1.992, 3.608, 9.267, 3.198, 9.155, 7.360, 1.040, 8.718, 12.187, 7.530, 1.015, 10.065, 4.460, 1.013, 2.410, 12.427, 6.285, 4.381, 6.183, 5.606, 4.754, 8.354, 1.448, 3.085, 10.088, 6.632, 3.148, 1.093, 5.326, 7.457, 4.247, 1.048, 3.691, 4.816, 6.333, 4.631, 10.221, 1.033, 7.962, 12.001, 1.970, 1.292, 3.876, 4.620, 8.946, 8.546, 6.226, 7.352, 11.847, 10.881, 1.841, 9.127, 5.410, 1.011, 3.286, 10.532, 7.975, 7.275, 3.916, 4.358, 1.047, 1.039, 2.088, 5.526, 1.016, 5.162, 1.584, 2.111, 12.576, 9.820, 5.213, 1.059, 10.777, 5.468, 11.687, 6.800, 8.066, 3.314, 6.770, 1.011, 2.660, 1.079, 5.259, 9.529, 5.701, 10.943, 1.353, 12.989, 1.028, 10.840, 1.038, 8.986, 10.336, 2.677, 3.228, 7.029, 11.665, 11.922, 11.254, 3.612, 1.047, 2.005, 1.013, 6.973, 9.665, 9.889, 10.196, 7.149, 12.090, 2.506, 10.366, 3.785, 10.387, 1.856, 11.823, 3.496, 2.832, 1.089, 6.341, 12.678, 1.586, 13.488, 8.128, 2.157, 2.401, 10.523, 1.299, 5.880, 12.341, 1.013, 5.525, 1.212, 4.093, 11.616, 8.362, 3.103, 3.446, 4.516, 9.831, 9.978, 11.452, 2.403, 10.692, 1.023, 1.028, 7.574, 12.034, 8.578, 11.426, 8.418, 1.056, 7.236, 3.420, 9.132, 7.626, 10.769, 1.068, 13.542, 6.438, 3.698, 13.685, 13.604, 1.061, 9.147, 3.384, 9.278, 13.617, 7.724, 1.041, 5.027, 5.348, 4.567, 1.028, 9.785, 3.817, 2.920, 1.110, 9.699, 13.723, 12.107, 3.152, 3.604, 7.487, 5.095, 4.261, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]

card_text = [None,["1"," Aegis Angel"," Creature - Angel "," 4WW"," 6"," 5/5"," Flying ,When Aegis Angel enters the battlefield, another target permanent is indestructible for as long as you control Aegis Angel. (Effects that say \"destroy\" don't destroy that permanent. An indestructible creature can't be destroyed by damage.) "],
    ["2"," Alabaster Mage"," Creature - Human Wizard "," 1W"," 2"," 2/1"," {1}{W}: Target creature you control gains lifelink until end of turn. (Damage dealt by the creature also causes its controller to gain that much life.) "],
    ["3"," Angelic Destiny"," Enchantment - Aura "," 2WW"," 4"," None"," Enchant creature ,Enchanted creature gets +4/+4, has flying and first strike, and is an Angel in addition to its other types. ,When enchanted creature dies, return Angelic Destiny to its owner's hand. "],
    ["4"," Angel's Mercy"," Instant "," 2WW"," 4"," None"," You gain 7 life. "],
    ["5"," Arbalest Elite"," Creature - Human Archer "," 2WW"," 4"," 2/3"," {2}{W}, {T}: Arbalest Elite deals 3 damage to target attacking or blocking creature. Arbalest Elite doesn't untap during your next untap step. "],
    ["6"," Archon of Justice"," Creature - Archon "," 3WW"," 5"," 4/4"," Flying ,When Archon of Justice dies, exile target permanent. "],
    ["7"," Armored Warhorse"," Creature - Horse "," WW"," 2"," 2/3","  "],
    ["8"," Assault Griffin"," Creature - Griffin "," 3W"," 4"," 3/2"," Flying "],
    ["9"," Auramancer"," Creature - Human Wizard "," 2W"," 3"," 2/2"," When Auramancer enters the battlefield, you may return target enchantment card from your graveyard to your hand. "],
    ["10"," Benalish Veteran"," Creature - Human Soldier "," 2W"," 3"," 2/2"," Whenever Benalish Veteran attacks, it gets +1/+1 until end of turn. "],
    ["11"," Celestial Purge"," Instant "," 1W"," 2"," None"," Exile target black or red permanent. "],
    ["12"," Day of Judgment"," Sorcery "," 2WW"," 4"," None"," Destroy all creatures. "],
    ["13"," Demystify"," Instant "," W"," 1"," None"," Destroy target enchantment. "],
    ["14"," Divine Favor"," Enchantment - Aura "," 1W"," 2"," None"," Enchant creature ,When Divine Favor enters the battlefield, you gain 3 life. ,Enchanted creature gets +1/+3. "],
    ["15"," Elite Vanguard"," Creature - Human Soldier "," W"," 1"," 2/1","  "],
    ["16"," Gideon Jura"," Planeswalker - Gideon "," 3WW"," 5"," None"," +2: During target opponent's next turn, creatures that player controls attack Gideon Jura if able. ,-2: Destroy target tapped creature. ,0: Until end of turn, Gideon Jura becomes a 6/6 Human Soldier creature that's still a planeswalker. Prevent all damage that would be dealt to him this turn. "],
    ["17"," Gideon's Avenger"," Creature - Human Soldier "," 1WW"," 3"," 2/2"," Whenever a creature an opponent controls becomes tapped, put a +1/+1 counter on Gideon's Avenger. "],
    ["18"," Gideon's Lawkeeper"," Creature - Human Soldier "," W"," 1"," 1/1"," {W}, {T}: Tap target creature. "],
    ["19"," Grand Abolisher"," Creature - Human Cleric "," WW"," 2"," 2/2"," During your turn, your opponents can't cast spells or activate abilities of artifacts, creatures, or enchantments. "],
    ["20"," Griffin Rider"," Creature - Human Knight "," 1W"," 2"," 1/1"," As long as you control a Griffin creature, Griffin Rider gets +3/+3 and has flying. "],
    ["21"," Griffin Sentinel"," Creature - Griffin "," 2W"," 3"," 1/3"," Flying ,Vigilance (Attacking doesn't cause this creature to tap.) "],
    ["22"," Guardians' Pledge"," Instant "," 1WW"," 3"," None"," White creatures you control get +2/+2 until end of turn. "],
    ["23"," Honor of the Pure"," Enchantment "," 1W"," 2"," None"," White creatures you control get +1/+1. "],
    ["24"," Lifelink"," Enchantment - Aura "," W"," 1"," None"," Enchant creature ,Enchanted creature has lifelink. (Damage dealt by the creature also causes its controller to gain that much life.) "],
    ["25"," Mesa Enchantress"," Creature - Human Druid "," 1WW"," 3"," 0/2"," Whenever you cast an enchantment spell, you may draw a card. "],
    ["26"," Mighty Leap"," Instant "," 1W"," 2"," None"," Target creature gets +2/+2 and gains flying until end of turn. "],
    ["27"," Oblivion Ring"," Enchantment "," 2W"," 3"," None"," When Oblivion Ring enters the battlefield, exile another target nonland permanent. ,When Oblivion Ring leaves the battlefield, return the exiled card to the battlefield under its owner's control. "],
    ["28"," Pacifism"," Enchantment - Aura "," 1W"," 2"," None"," Enchant creature ,Enchanted creature can't attack or block. "],
    ["29"," Peregrine Griffin"," Creature - Griffin "," 4W"," 5"," 2/4"," Flying ,First strike (This creature deals combat damage before creatures without first strike.) "],
    ["30"," Personal Sanctuary"," Enchantment "," 2W"," 3"," None"," During your turn, prevent all damage that would be dealt to you. "],
    ["31"," Pride Guardian"," Creature - Cat Monk "," W"," 1"," 0/3"," Defender (This creature can't attack.) ,Whenever Pride Guardian blocks, you gain 3 life. "],
    ["32"," Roc Egg"," Creature - Bird "," 2W"," 3"," 0/3"," Defender (This creature can't attack.) ,When Roc Egg dies, put a 3/3 white Bird creature token with flying onto the battlefield. "],
    ["33"," Serra Angel"," Creature - Angel "," 3WW"," 5"," 4/4"," Flying ,Vigilance (Attacking doesn't cause this creature to tap.) "],
    ["34"," Siege Mastodon"," Creature - Elephant "," 4W"," 5"," 3/5","  "],
    ["35"," Spirit Mantle"," Enchantment - Aura "," 1W"," 2"," None"," Enchant creature ,Enchanted creature gets +1/+1 and has protection from creatures. (It can't be blocked, targeted, or dealt damage by creatures.) "],
    ["36"," Stave Off"," Instant "," W"," 1"," None"," Target creature gains protection from the color of your choice until end of turn. (It can't be blocked, targeted, dealt damage, or enchanted by anything of that color.) "],
    ["37"," Stonehorn Dignitary"," Creature - Rhino Soldier "," 3W"," 4"," 1/4"," When Stonehorn Dignitary enters the battlefield, target opponent skips his or her next combat phase. "],
    ["38"," Stormfront Pegasus"," Creature - Pegasus "," 1W"," 2"," 2/1"," Flying "],
    ["39"," Sun Titan"," Creature - Giant "," 4WW"," 6"," 6/6"," Vigilance ,Whenever Sun Titan enters the battlefield or attacks, you may return target permanent card with converted mana cost 3 or less from your graveyard to the battlefield. "],
    ["40"," Timely Reinforcements"," Sorcery "," 2W"," 3"," None"," If you have less life than an opponent, you gain 6 life. If you control fewer creatures than an opponent, put three 1/1 white Soldier creature tokens onto the battlefield. "],
    ["41"," Aether Adept"," Creature - Human Wizard "," 1UU"," 3"," 2/2"," When Aether Adept enters the battlefield, return target creature to its owner's hand. "],
    ["42"," Alluring Siren"," Creature - Siren "," 1U"," 2"," 1/1"," {T}: Target creature an opponent controls attacks you this turn if able. "],
    ["43"," Amphin Cutthroat"," Creature - Salamander Rogue "," 3U"," 4"," 2/4","  "],
    ["44"," Aven Fleetwing"," Creature - Bird Soldier "," 3U"," 4"," 2/2"," Flying ,Hexproof (This creature can't be the target of spells or abilities your opponents control.) "],
    ["45"," Azure Mage"," Creature - Human Wizard "," 1U"," 2"," 2/1"," {3}{U}: Draw a card. "],
    ["46"," Belltower Sphinx"," Creature - Sphinx "," 4U"," 5"," 2/5"," Flying ,Whenever a source deals damage to Belltower Sphinx, that source's controller puts that many cards from the top of his or her library into his or her graveyard. "],
    ["47"," Cancel"," Instant "," 1UU"," 3"," None"," Counter target spell. "],
    ["48"," Chasm Drake"," Creature - Drake "," 4U"," 5"," 3/3"," Flying ,Whenever Chasm Drake attacks, target creature you control gains flying until end of turn. "],
    ["49"," Coral Merfolk"," Creature - Merfolk "," 1U"," 2"," 2/1","  "],
    ["50"," Divination"," Sorcery "," 2U"," 3"," None"," Draw two cards. "],
    ["51"," Djinn of Wishes"," Creature - Djinn "," 3UU"," 5"," 4/4"," Flying ,Djinn of Wishes enters the battlefield with three wish counters on it. ,{2}{U}{U}, Remove a wish counter from Djinn of Wishes: Reveal the top card of your library. You may play that card without paying its mana cost. If you don't, exile it. "],
    ["52"," Flashfreeze"," Instant "," 1U"," 2"," None"," Counter target red or green spell. "],
    ["53"," Flight"," Enchantment - Aura "," U"," 1"," None"," Enchant creature ,Enchanted creature has flying. "],
    ["54"," Frost Breath"," Instant "," 2U"," 3"," None"," Tap up to two target creatures. Those creatures don't untap during their controller's next untap step. "],
    ["55"," Frost Titan"," Creature - Giant "," 4UU"," 6"," 6/6"," Whenever Frost Titan becomes the target of a spell or ability an opponent controls, counter that spell or ability unless its controller pays {2}. ,Whenever Frost Titan enters the battlefield or attacks, tap target permanent. It doesn't untap during its controller's next untap step. "],
    ["56"," Harbor Serpent"," Creature - Serpent "," 4UU"," 6"," 5/5"," Islandwalk (This creature is unblockable as long as defending player controls an Island.) ,Harbor Serpent can't attack unless there are five or more Islands on the battlefield. "],
    ["57"," Ice Cage"," Enchantment - Aura "," 1U"," 2"," None"," Enchant creature ,Enchanted creature can't attack or block, and its activated abilities can't be activated. ,When enchanted creature becomes the target of a spell or ability, destroy Ice Cage. "],
    ["58"," Jace, Memory Adept"," Planeswalker - Jace "," 3UU"," 5"," None"," +1: Draw a card. Target player puts the top card of his or her library into his or her graveyard. ,0: Target player puts the top ten cards of his or her library into his or her graveyard. ,-7: Any number of target players each draw twenty cards. "],
    ["59"," Jace's Archivist"," Creature - Vedalken Wizard "," 1UU"," 3"," 2/2"," {U}, {T}: Each player discards his or her hand, then draws cards equal to the greatest number of cards a player discarded this way. "],
    ["60"," Jace's Erasure"," Enchantment "," 1U"," 2"," None"," Whenever you draw a card, you may have target player put the top card of his or her library into his or her graveyard. "],
    ["61"," Levitation"," Enchantment "," 2UU"," 4"," None"," Creatures you control have flying. "],
    ["62"," Lord of the Unreal"," Creature - Human Wizard "," UU"," 2"," 2/2"," Illusion creatures you control get +1/+1 and have hexproof. (They can't be the targets of spells or abilities your opponents control.) "],
    ["63"," Mana Leak"," Instant "," 1U"," 2"," None"," Counter target spell unless its controller pays {3}. "],
    ["64"," Master Thief"," Creature - Human Rogue "," 2UU"," 4"," 2/2"," When Master Thief enters the battlefield, gain control of target artifact for as long as you control Master Thief. "],
    ["65"," Merfolk Looter"," Creature - Merfolk Rogue "," 1U"," 2"," 1/1"," {T}: Draw a card, then discard a card. "],
    ["66"," Merfolk Mesmerist"," Creature - Merfolk Wizard "," 1U"," 2"," 1/2"," {U}, {T}: Target player puts the top two cards of his or her library into his or her graveyard. "],
    ["67"," Mind Control"," Enchantment - Aura "," 3UU"," 5"," None"," Enchant creature ,You control enchanted creature. "],
    ["68"," Mind Unbound"," Enchantment "," 4UU"," 6"," None"," At the beginning of your upkeep, put a lore counter on Mind Unbound, then draw a card for each lore counter on Mind Unbound. "],
    ["69"," Negate"," Instant "," 1U"," 2"," None"," Counter target noncreature spell. "],
    ["70"," Phantasmal Bear"," Creature - Bear Illusion "," U"," 1"," 2/2"," When Phantasmal Bear becomes the target of a spell or ability, sacrifice it. "],
    ["71"," Phantasmal Dragon"," Creature - Dragon Illusion "," 2UU"," 4"," 5/5"," Flying ,When Phantasmal Dragon becomes the target of a spell or ability, sacrifice it. "],
    ["72"," Phantasmal Image"," Creature - Illusion "," 1U"," 2"," 0/0"," You may have Phantasmal Image enter the battlefield as a copy of any creature on the battlefield, except it's an Illusion in addition to its other types and it gains \"When this creature becomes the target of a spell or ability, sacrifice it.\" "],
    ["73"," Ponder"," Sorcery "," U"," 1"," None"," Look at the top three cards of your library, then put them back in any order. You may shuffle your library. ,Draw a card. "],
    ["74"," Redirect"," Instant "," UU"," 2"," None"," You may choose new targets for target spell. "],
    ["75"," Skywinder Drake"," Creature - Drake "," 2U"," 3"," 3/1"," Flying ,Skywinder Drake can block only creatures with flying. "],
    ["76"," Sphinx of Uthuun"," Creature - Sphinx "," 5UU"," 7"," 5/6"," Flying ,When Sphinx of Uthuun enters the battlefield, reveal the top five cards of your library. An opponent separates those cards into two piles. Put one pile into your hand and the other into your graveyard. "],
    ["77"," Time Reversal"," Sorcery "," 3UU"," 5"," None"," Each player shuffles his or her hand and graveyard into his or her library, then draws seven cards. Exile Time Reversal. "],
    ["78"," Turn to Frog"," Instant "," 1U"," 2"," None"," Target creature loses all abilities and becomes a 1/1 blue Frog until end of turn. "],
    ["79"," Unsummon"," Instant "," U"," 1"," None"," Return target creature to its owner's hand. "],
    ["80"," Visions of Beyond"," Instant "," U"," 1"," None"," Draw a card. If a graveyard has twenty or more cards in it, draw three cards instead. "],
    ["81"," Blood Seeker"," Creature - Vampire Shaman "," 1B"," 2"," 1/1"," Whenever a creature enters the battlefield under an opponent's control, you may have that player lose 1 life. "],
    ["82"," Bloodlord of Vaasgoth"," Creature - Vampire Warrior "," 3BB"," 5"," 3/3"," Bloodthirst 3 (If an opponent was dealt damage this turn, this creature enters the battlefield with three +1/+1 counters on it.) ,Flying ,Whenever you cast a Vampire creature spell, it gains bloodthirst 3. "],
    ["83"," Bloodrage Vampire"," Creature - Vampire "," 2B"," 3"," 3/1"," Bloodthirst 1 (If an opponent was dealt damage this turn, this creature enters the battlefield with a +1/+1 counter on it.) "],
    ["84"," Brink of Disaster"," Enchantment - Aura "," 2BB"," 4"," None"," Enchant creature or land ,When enchanted permanent becomes tapped, destroy it. "],
    ["85"," Call to the Grave"," Enchantment "," 4B"," 5"," None"," At the beginning of each player's upkeep, that player sacrifices a non-Zombie creature. ,At the beginning of the end step, if no creatures are on the battlefield, sacrifice Call to the Grave. "],
    ["86"," Cemetery Reaper"," Creature - Zombie "," 1BB"," 3"," 2/2"," Other Zombie creatures you control get +1/+1. ,{2}{B}, {T}: Exile target creature card from a graveyard. Put a 2/2 black Zombie creature token onto the battlefield. "],
    ["87"," Child of Night"," Creature - Vampire "," 1B"," 2"," 2/1"," Lifelink (Damage dealt by this creature also causes you to gain that much life.) "],
    ["88"," Consume Spirit"," Sorcery "," X1B"," 2"," None"," Spend only black mana on X. ,Consume Spirit deals X damage to target creature or player and you gain X life. "],
    ["89"," Dark Favor"," Enchantment - Aura "," 1B"," 2"," None"," Enchant creature ,When Dark Favor enters the battlefield, you lose 1 life. ,Enchanted creature gets +3/+1. "],
    ["90"," Deathmark"," Sorcery "," B"," 1"," None"," Destroy target green or white creature. "],
    ["91"," Devouring Swarm"," Creature - Insect "," 1BB"," 3"," 2/1"," Flying ,Sacrifice a creature: Devouring Swarm gets +1/+1 until end of turn. "],
    ["92"," Diabolic Tutor"," Sorcery "," 2BB"," 4"," None"," Search your library for a card and put that card into your hand. Then shuffle your library. "],
    ["93"," Disentomb"," Sorcery "," B"," 1"," None"," Return target creature card from your graveyard to your hand. "],
    ["94"," Distress"," Sorcery "," BB"," 2"," None"," Target player reveals his or her hand. You choose a nonland card from it. That player discards that card. "],
    ["95"," Doom Blade"," Instant "," 1B"," 2"," None"," Destroy target nonblack creature. "],
    ["96"," Drifting Shade"," Creature - Shade "," 3B"," 4"," 1/1"," Flying ,{B}: Drifting Shade gets +1/+1 until end of turn. "],
    ["97"," Duskhunter Bat"," Creature - Bat "," 1B"," 2"," 1/1"," Bloodthirst 1 (If an opponent was dealt damage this turn, this creature enters the battlefield with a +1/+1 counter on it.) ,Flying "],
    ["98"," Grave Titan"," Creature - Giant "," 4BB"," 6"," 6/6"," Deathtouch ,Whenever Grave Titan enters the battlefield or attacks, put two 2/2 black Zombie creature tokens onto the battlefield. "],
    ["99"," Gravedigger"," Creature - Zombie "," 3B"," 4"," 2/2"," When Gravedigger enters the battlefield, you may return target creature card from your graveyard to your hand. "],
    ["100"," Hideous Visage"," Sorcery "," 2B"," 3"," None"," Creatures you control gain intimidate until end of turn. (Each of those creatures can't be blocked except by artifact creatures and/or creatures that share a color with it.) "],
    ["101"," Mind Rot"," Sorcery "," 2B"," 3"," None"," Target player discards two cards. "],
    ["102"," Monomania"," Sorcery "," 3BB"," 5"," None"," Target player chooses a card in his or her hand and discards the rest. "],
    ["103"," Onyx Mage"," Creature - Human Wizard "," 1B"," 2"," 2/1"," {1}{B}: Target creature you control gains deathtouch until end of turn. (Any amount of damage it deals to a creature is enough to destroy it.) "],
    ["104"," Reassembling Skeleton"," Creature - Skeleton Warrior "," 1B"," 2"," 1/1"," {1}{B}: Return Reassembling Skeleton from your graveyard to the battlefield tapped. "],
    ["105"," Royal Assassin"," Creature - Human Assassin "," 1BB"," 3"," 1/1"," {T}: Destroy target tapped creature. "],
    ["106"," Rune-Scarred Demon"," Creature - Demon "," 5BB"," 7"," 6/6"," Flying ,When Rune-Scarred Demon enters the battlefield, search your library for a card, put it into your hand, then shuffle your library. "],
    ["107"," Sengir Vampire"," Creature - Vampire "," 3BB"," 5"," 4/4"," Flying ,Whenever a creature dealt damage by Sengir Vampire this turn dies, put a +1/+1 counter on Sengir Vampire. "],
    ["108"," Smallpox"," Sorcery "," BB"," 2"," None"," Each player loses 1 life, discards a card, sacrifices a creature, then sacrifices a land. "],
    ["109"," Sorin Markov"," Planeswalker - Sorin "," 3BBB"," 6"," None"," +2: Sorin Markov deals 2 damage to target creature or player and you gain 2 life. ,-3: Target opponent's life total becomes 10. ,-7: You control target player during that player's next turn. "],
    ["110"," Sorin's Thirst"," Instant "," BB"," 2"," None"," Sorin's Thirst deals 2 damage to target creature and you gain 2 life. "],
    ["111"," Sorin's Vengeance"," Sorcery "," 4BBB"," 7"," None"," Sorin's Vengeance deals 10 damage to target player and you gain 10 life. "],
    ["112"," Sutured Ghoul"," Creature - Zombie "," 4BBB"," 7"," */*"," Trample ,As Sutured Ghoul enters the battlefield, exile any number of creature cards from your graveyard. ,Sutured Ghoul's power is equal to the total power of the exiled cards and its toughness is equal to their total toughness. "],
    ["113"," Taste of Blood"," Sorcery "," B"," 1"," None"," Taste of Blood deals 1 damage to target player and you gain 1 life. "],
    ["114"," Tormented Soul"," Creature - Spirit "," B"," 1"," 1/1"," Tormented Soul can't block and is unblockable. "],
    ["115"," Vampire Outcasts"," Creature - Vampire "," 2BB"," 4"," 2/2"," Bloodthirst 2 (If an opponent was dealt damage this turn, this creature enters the battlefield with two +1/+1 counters on it.) ,Lifelink (Damage dealt by this creature also causes you to gain that much life.) "],
    ["116"," Vengeful Pharaoh"," Creature - Zombie "," 2BBB"," 5"," 5/4"," Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) ,Whenever combat damage is dealt to you or a planeswalker you control, if Vengeful Pharaoh is in your graveyard, destroy target attacking creature, then put Vengeful Pharaoh on top of your library. "],
    ["117"," Warpath Ghoul"," Creature - Zombie "," 2B"," 3"," 3/2","  "],
    ["118"," Wring Flesh"," Instant "," B"," 1"," None"," Target creature gets -3/-1 until end of turn. "],
    ["119"," Zombie Goliath"," Creature - Zombie Giant "," 4B"," 5"," 4/3","  "],
    ["120"," Zombie Infestation"," Enchantment "," 1B"," 2"," None"," Discard two cards: Put a 2/2 black Zombie creature token onto the battlefield. "],
    ["121"," Act of Treason"," Sorcery "," 2R"," 3"," None"," Gain control of target creature until end of turn. Untap that creature. It gains haste until end of turn. (It can attack and {T} this turn.) "],
    ["122"," Blood Ogre"," Creature - Ogre Warrior "," 2R"," 3"," 2/2"," Bloodthirst 1 (If an opponent was dealt damage this turn, this creature enters the battlefield with a +1/+1 counter on it.) ,First strike (This creature deals combat damage before creatures without first strike.) "],
    ["123"," Bonebreaker Giant"," Creature - Giant "," 4R"," 5"," 4/4","  "],
    ["124"," Chandra, the Firebrand"," Planeswalker - Chandra "," 3R"," 4"," None"," +1: Chandra, the Firebrand deals 1 damage to target creature or player. ,-2: When you cast your next instant or sorcery spell this turn, copy that spell. You may choose new targets for the copy. ,-6: Chandra, the Firebrand deals 6 damage to each of up to six target creatures and/or players. "],
    ["125"," Chandra's Outrage"," Instant "," 2RR"," 4"," None"," Chandra's Outrage deals 4 damage to target creature and 2 damage to that creature's controller. "],
    ["126"," Chandra's Phoenix"," Creature - Phoenix "," 1RR"," 3"," 2/2"," Flying ,Haste (This creature can attack and {T} as soon as it comes under your control.) ,Whenever an opponent is dealt damage by a red instant or sorcery spell you control or by a red planeswalker you control, return Chandra's Phoenix from your graveyard to your hand. "],
    ["127"," Circle of Flame"," Enchantment "," 1R"," 2"," None"," Whenever a creature without flying attacks you or a planeswalker you control, Circle of Flame deals 1 damage to that creature. "],
    ["128"," Combust"," Instant "," 1R"," 2"," None"," Combust can't be countered by spells or abilities. ,Combust deals 5 damage to target white or blue creature. The damage can't be prevented. "],
    ["129"," Crimson Mage"," Creature - Human Shaman "," 1R"," 2"," 2/1"," {R}: Target creature you control gains haste until end of turn. (It can attack and {T} this turn.) "],
    ["130"," Fiery Hellhound"," Creature - Elemental Hound "," 1RR"," 3"," 2/2"," {R}: Fiery Hellhound gets +1/+0 until end of turn. "],
    ["131"," Fireball"," Sorcery "," XR"," 1"," None"," Fireball deals X damage divided evenly, rounded down, among any number of target creatures and/or players. ,Fireball costs {1} more to cast for each target beyond the first. "],
    ["132"," Firebreathing"," Enchantment - Aura "," R"," 1"," None"," Enchant creature ,{R}: Enchanted creature gets +1/+0 until end of turn. "],
    ["133"," Flameblast Dragon"," Creature - Dragon "," 4RR"," 6"," 5/5"," Flying ,Whenever Flameblast Dragon attacks, you may pay {X}{R}. If you do, Flameblast Dragon deals X damage to target creature or player. "],
    ["134"," Fling"," Instant "," 1R"," 2"," None"," As an additional cost to cast Fling, sacrifice a creature. ,Fling deals damage equal to the sacrificed creature's power to target creature or player. "],
    ["135"," Furyborn Hellkite"," Creature - Dragon "," 4RRR"," 7"," 6/6"," Bloodthirst 6 (If an opponent was dealt damage this turn, this creature enters the battlefield with six +1/+1 counters on it.) ,Flying "],
    ["136"," Goblin Arsonist"," Creature - Goblin Shaman "," R"," 1"," 1/1"," When Goblin Arsonist dies, you may have it deal 1 damage to target creature or player. "],
    ["137"," Goblin Bangchuckers"," Creature - Goblin Warrior "," 2RR"," 4"," 2/2"," {T}: Flip a coin. If you win the flip, Goblin Bangchuckers deals 2 damage to target creature or player. If you lose the flip, Goblin Bangchuckers deals 2 damage to itself. "],
    ["138"," Goblin Chieftain"," Creature - Goblin "," 1RR"," 3"," 2/2"," Haste (This creature can attack and {T} as soon as it comes under your control.) ,Other Goblin creatures you control get +1/+1 and have haste. "],
    ["139"," Goblin Fireslinger"," Creature - Goblin Warrior "," R"," 1"," 1/1"," {T}: Goblin Fireslinger deals 1 damage to target player. "],
    ["140"," Goblin Grenade"," Sorcery "," R"," 1"," None"," As an additional cost to cast Goblin Grenade, sacrifice a Goblin. ,Goblin Grenade deals 5 damage to target creature or player. "],
    ["141"," Goblin Piker"," Creature - Goblin Warrior "," 1R"," 2"," 2/1","  "],
    ["142"," Goblin Tunneler"," Creature - Goblin Rogue "," 1R"," 2"," 1/1"," {T}: Target creature with power 2 or less is unblockable this turn. "],
    ["143"," Goblin War Paint"," Enchantment - Aura "," 1R"," 2"," None"," Enchant creature ,Enchanted creature gets +2/+2 and has haste. (It can attack and {T} no matter when it came under its controller's control.) "],
    ["144"," Gorehorn Minotaurs"," Creature - Minotaur Warrior "," 2RR"," 4"," 3/3"," Bloodthirst 2 (If an opponent was dealt damage this turn, this creature enters the battlefield with two +1/+1 counters on it.) "],
    ["145"," Grim Lavamancer"," Creature - Human Wizard "," R"," 1"," 1/1"," {R}, {T}, Exile two cards from your graveyard: Grim Lavamancer deals 2 damage to target creature or player. "],
    ["146"," Incinerate"," Instant "," 1R"," 2"," None"," Incinerate deals 3 damage to target creature or player. A creature dealt damage this way can't be regenerated this turn. "],
    ["147"," Inferno Titan"," Creature - Giant "," 4RR"," 6"," 6/6"," {R}: Inferno Titan gets +1/+0 until end of turn. ,Whenever Inferno Titan enters the battlefield or attacks, it deals 3 damage divided as you choose among one, two, or three target creatures and/or players. "],
    ["148"," Lava Axe"," Sorcery "," 4R"," 5"," None"," Lava Axe deals 5 damage to target player. "],
    ["149"," Lightning Elemental"," Creature - Elemental "," 3R"," 4"," 4/1"," Haste (This creature can attack and {T} as soon as it comes under your control.) "],
    ["150"," Manabarbs"," Enchantment "," 3R"," 4"," None"," Whenever a player taps a land for mana, Manabarbs deals 1 damage to that player. "],
    ["151"," Manic Vandal"," Creature - Human Warrior "," 2R"," 3"," 2/2"," When Manic Vandal enters the battlefield, destroy target artifact. "],
    ["152"," Reverberate"," Instant "," RR"," 2"," None"," Copy target instant or sorcery spell. You may choose new targets for the copy. "],
    ["153"," Scrambleverse"," Sorcery "," 6RR"," 8"," None"," For each nonland permanent, choose a player at random. Then each player gains control of each permanent for which he or she was chosen. Untap those permanents. "],
    ["154"," Shock"," Instant "," R"," 1"," None"," Shock deals 2 damage to target creature or player. "],
    ["155"," Slaughter Cry"," Instant "," 2R"," 3"," None"," Target creature gets +3/+0 and gains first strike until end of turn. (It deals combat damage before creatures without first strike.) "],
    ["156"," Stormblood Berserker"," Creature - Human Berserker "," 1R"," 2"," 1/1"," Bloodthirst 2 (If an opponent was dealt damage this turn, this creature enters the battlefield with two +1/+1 counters on it.) ,Stormblood Berserker can't be blocked except by two or more creatures. "],
    ["157"," Tectonic Rift"," Sorcery "," 3R"," 4"," None"," Destroy target land. Creatures without flying can't block this turn. "],
    ["158"," Volcanic Dragon"," Creature - Dragon "," 4RR"," 6"," 4/4"," Flying ,Haste (This creature can attack and {T} as soon as it comes under your control.) "],
    ["159"," Wall of Torches"," Creature - Wall "," 1R"," 2"," 4/1"," Defender (This creature can't attack.) "],
    ["160"," Warstorm Surge"," Enchantment "," 5R"," 6"," None"," Whenever a creature enters the battlefield under your control, it deals damage equal to its power to target creature or player. "],
    ["161"," Acidic Slime"," Creature - Ooze "," 3GG"," 5"," 2/2"," Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) ,When Acidic Slime enters the battlefield, destroy target artifact, enchantment, or land. "],
    ["162"," Arachnus Spinner"," Creature - Spider "," 5G"," 6"," 5/7"," Reach (This creature can block creatures with flying.) ,Tap an untapped Spider you control: Search your graveyard and/or library for a card named Arachnus Web and put it onto the battlefield attached to target creature. If you search your library this way, shuffle it. "],
    ["163"," Arachnus Web"," Enchantment - Aura "," 2G"," 3"," None"," Enchant creature ,Enchanted creature can't attack or block, and its activated abilities can't be activated. ,At the beginning of the end step, if enchanted creature's power is 4 or greater, destroy Arachnus Web. "],
    ["164"," Autumn's Veil"," Instant "," G"," 1"," None"," Spells you control can't be countered by blue or black spells this turn, and creatures you control can't be the targets of blue or black spells this turn. "],
    ["165"," Birds of Paradise"," Creature - Bird "," G"," 1"," 0/1"," Flying ,{T}: Add one mana of any color to your mana pool. "],
    ["166"," Bountiful Harvest"," Sorcery "," 4G"," 5"," None"," You gain 1 life for each land you control. "],
    ["167"," Brindle Boar"," Creature - Boar "," 2G"," 3"," 2/2"," Sacrifice Brindle Boar: You gain 4 life. "],
    ["168"," Carnage Wurm"," Creature - Wurm "," 6G"," 7"," 6/6"," Bloodthirst 3 (If an opponent was dealt damage this turn, this creature enters the battlefield with three +1/+1 counters on it.) ,Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.) "],
    ["169"," Cudgel Troll"," Creature - Troll "," 2GG"," 4"," 4/3"," {G}: Regenerate Cudgel Troll. (The next time this creature would be destroyed this turn, it isn't. Instead tap it, remove all damage from it, and remove it from combat.) "],
    ["170"," Doubling Chant"," Sorcery "," 5G"," 6"," None"," For each creature you control, you may search your library for a creature card with the same name as that creature. Put those cards onto the battlefield, then shuffle your library. "],
    ["171"," Dungrove Elder"," Creature - Treefolk "," 2G"," 3"," */*"," Hexproof (This creature can't be the target of spells or abilities your opponents control.) ,Dungrove Elder's power and toughness are each equal to the number of Forests you control. "],
    ["172"," Elvish Archdruid"," Creature - Elf Druid "," 1GG"," 3"," 2/2"," Other Elf creatures you control get +1/+1. ,{T}: Add {G} to your mana pool for each Elf you control. "],
    ["173"," Fog"," Instant "," G"," 1"," None"," Prevent all combat damage that would be dealt this turn. "],
    ["174"," Garruk, Primal Hunter"," Planeswalker - Garruk "," 2GGG"," 5"," None"," +1: Put a 3/3 green Beast creature token onto the battlefield. ,-3: Draw cards equal to the greatest power among creatures you control. ,-6: Put a 6/6 green Wurm creature token onto the battlefield for each land you control. "],
    ["175"," Garruk's Companion"," Creature - Beast "," GG"," 2"," 3/2"," Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.) "],
    ["176"," Garruk's Horde"," Creature - Beast "," 5GG"," 7"," 7/7"," Trample ,Play with the top card of your library revealed. ,You may cast the top card of your library if it's a creature card. (Do this only any time you could cast that creature card. You still pay the spell's costs.) "],
    ["177"," Giant Spider"," Creature - Spider "," 3G"," 4"," 2/4"," Reach (This creature can block creatures with flying.) "],
    ["178"," Gladecover Scout"," Creature - Elf Scout "," G"," 1"," 1/1"," Hexproof (This creature can't be the target of spells or abilities your opponents control.) "],
    ["179"," Greater Basilisk"," Creature - Basilisk "," 3GG"," 5"," 3/5"," Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) "],
    ["180"," Hunter's Insight"," Instant "," 2G"," 3"," None"," Choose target creature you control. Whenever that creature deals combat damage to a player or planeswalker this turn, draw that many cards. "],
    ["181"," Jade Mage"," Creature - Human Shaman "," 1G"," 2"," 2/1"," {2}{G}: Put a 1/1 green Saproling creature token onto the battlefield. "],
    ["182"," Llanowar Elves"," Creature - Elf Druid "," G"," 1"," 1/1"," {T}: Add {G} to your mana pool. "],
    ["183"," Lure"," Enchantment - Aura "," 1GG"," 3"," None"," Enchant creature ,All creatures able to block enchanted creature do so. "],
    ["184"," Lurking Crocodile"," Creature - Crocodile "," 2G"," 3"," 2/2"," Bloodthirst 1 (If an opponent was dealt damage this turn, this creature enters the battlefield with a +1/+1 counter on it.) ,Islandwalk (This creature is unblockable as long as defending player controls an Island.) "],
    ["185"," Naturalize"," Instant "," 1G"," 2"," None"," Destroy target artifact or enchantment. "],
    ["186"," Overrun"," Sorcery "," 2GGG"," 5"," None"," Creatures you control get +3/+3 and gain trample until end of turn. (If a creature you control would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.) "],
    ["187"," Plummet"," Instant "," 1G"," 2"," None"," Destroy target creature with flying. "],
    ["188"," Primeval Titan"," Creature - Giant "," 4GG"," 6"," 6/6"," Trample ,Whenever Primeval Titan enters the battlefield or attacks, you may search your library for up to two land cards, put them onto the battlefield tapped, then shuffle your library. "],
    ["189"," Primordial Hydra"," Creature - Hydra "," XGG"," 2"," 0/0"," Primordial Hydra enters the battlefield with X +1/+1 counters on it. ,At the beginning of your upkeep, double the number of +1/+1 counters on Primordial Hydra. ,Primordial Hydra has trample as long as it has ten or more +1/+1 counters on it. "],
    ["190"," Rampant Growth"," Sorcery "," 1G"," 2"," None"," Search your library for a basic land card and put that card onto the battlefield tapped. Then shuffle your library. "],
    ["191"," Reclaim"," Instant "," G"," 1"," None"," Put target card from your graveyard on top of your library. "],
    ["192"," Rites of Flourishing"," Enchantment "," 2G"," 3"," None"," At the beginning of each player's draw step, that player draws an additional card. ,Each player may play an additional land on each of his or her turns. "],
    ["193"," Runeclaw Bear"," Creature - Bear "," 1G"," 2"," 2/2","  "],
    ["194"," Sacred Wolf"," Creature - Wolf "," 2G"," 3"," 3/1"," Hexproof (This creature can't be the target of spells or abilities your opponents control.) "],
    ["195"," Skinshifter"," Creature - Human Shaman "," 1G"," 2"," 1/1"," {G}: Choose one - Until end of turn, Skinshifter becomes a 4/4 Rhino and gains trample"," or until end of turn, Skinshifter becomes a 2/2 Bird and gains flying"," or until end of turn, Skinshifter becomes a 0/8 Plant. Activate this ability only once each turn. "],
    ["196"," Stampeding Rhino"," Creature - Rhino "," 4G"," 5"," 4/4"," Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.) "],
    ["197"," Stingerfling Spider"," Creature - Spider "," 4G"," 5"," 2/5"," Reach (This creature can block creatures with flying.) ,When Stingerfling Spider enters the battlefield, you may destroy target creature with flying. "],
    ["198"," Titanic Growth"," Instant "," 1G"," 2"," None"," Target creature gets +4/+4 until end of turn. "],
    ["199"," Trollhide"," Enchantment - Aura "," 2G"," 3"," None"," Enchant creature ,Enchanted creature gets +2/+2 and has \"{1}{G}: Regenerate this creature.\" (The next time the creature would be destroyed this turn, it isn't. Instead tap it, remove all damage from it, and remove it from combat.) "],
    ["200"," Vastwood Gorger"," Creature - Wurm "," 5G"," 6"," 5/6","  "],
    ["201"," Adaptive Automaton"," Artifact Creature - Construct "," 3"," 3"," 2/2"," As Adaptive Automaton enters the battlefield, choose a creature type. ,Adaptive Automaton is the chosen type in addition to its other types. ,Other creatures you control of the chosen type get +1/+1. "],
    ["202"," Angel's Feather"," Artifact "," 2"," 2"," None"," Whenever a player casts a white spell, you may gain 1 life. "],
    ["203"," Crown of Empires"," Artifact "," 2"," 2"," None"," {3}, {T}: Tap target creature. Gain control of that creature instead if you control artifacts named Scepter of Empires and Throne of Empires. "],
    ["204"," Crumbling Colossus"," Artifact Creature - Golem "," 5"," 5"," 7/4"," Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.) ,When Crumbling Colossus attacks, sacrifice it at end of combat. "],
    ["205"," Demon's Horn"," Artifact "," 2"," 2"," None"," Whenever a player casts a black spell, you may gain 1 life. "],
    ["206"," Dragon's Claw"," Artifact "," 2"," 2"," None"," Whenever a player casts a red spell, you may gain 1 life. "],
    ["207"," Druidic Satchel"," Artifact "," 3"," 3"," None"," {2}, {T}: Reveal the top card of your library. If it's a creature card, put a 1/1 green Saproling creature token onto the battlefield. If it's a land card, put that card onto the battlefield under your control. If it's a noncreature, nonland card, you gain 2 life. "],
    ["208"," Elixir of Immortality"," Artifact "," 1"," 1"," None"," {2}, {T}: You gain 5 life. Shuffle Elixir of Immortality and your graveyard into their owner's library. "],
    ["209"," Greatsword"," Artifact - Equipment "," 3"," 3"," None"," Equipped creature gets +3/+0. ,Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.) "],
    ["210"," Kite Shield"," Artifact - Equipment "," 0"," 0"," None"," Equipped creature gets +0/+3. ,Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.) "],
    ["211"," Kraken's Eye"," Artifact "," 2"," 2"," None"," Whenever a player casts a blue spell, you may gain 1 life. "],
    ["212"," Manalith"," Artifact "," 3"," 3"," None"," {T}: Add one mana of any color to your mana pool. "],
    ["213"," Pentavus"," Artifact Creature - Construct "," 7"," 7"," 0/0"," Pentavus enters the battlefield with five +1/+1 counters on it. ,{1}, Remove a +1/+1 counter from Pentavus: Put a 1/1 colorless Pentavite artifact creature token with flying onto the battlefield. ,{1}, Sacrifice a Pentavite: Put a +1/+1 counter on Pentavus. "],
    ["214"," Quicksilver Amulet"," Artifact "," 4"," 4"," None"," {4}, {T}: You may put a creature card from your hand onto the battlefield. "],
    ["215"," Rusted Sentinel"," Artifact Creature - Golem "," 4"," 4"," 3/4"," Rusted Sentinel enters the battlefield tapped. "],
    ["216"," Scepter of Empires"," Artifact "," 3"," 3"," None"," {T}: Scepter of Empires deals 1 damage to target player. It deals 3 damage to that player instead if you control artifacts named Crown of Empires and Throne of Empires. "],
    ["217"," Solemn Simulacrum"," Artifact Creature - Golem "," 4"," 4"," 2/2"," When Solemn Simulacrum enters the battlefield, you may search your library for a basic land card, put that card onto the battlefield tapped, then shuffle your library. ,When Solemn Simulacrum dies, you may draw a card. "],
    ["218"," Sundial of the Infinite"," Artifact "," 2"," 2"," None"," {1}, {T}: End the turn. Activate this ability only during your turn. (Exile all spells and abilities on the stack. Discard down to your maximum hand size. Damage wears off, and \"this turn\" and \"until end of turn\" effects end.) "],
    ["219"," Swiftfoot Boots"," Artifact - Equipment "," 2"," 2"," None"," Equipped creature has hexproof and haste. (It can't be the target of spells or abilities your opponents control, and it can attack and {T} as soon as it comes under your control.) ,Equip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.) "],
    ["220"," Thran Golem"," Artifact Creature - Golem "," 5"," 5"," 3/3"," As long as Thran Golem is enchanted, it gets +2/+2 and has flying, first strike, and trample. "],
    ["221"," Throne of Empires"," Artifact "," 4"," 4"," None"," {1}, {T}: Put a 1/1 white Soldier creature token onto the battlefield. Put five of those tokens onto the battlefield instead if you control artifacts named Crown of Empires and Scepter of Empires. "],
    ["222"," Worldslayer"," Artifact - Equipment "," 5"," 5"," None"," Whenever equipped creature deals combat damage to a player, destroy all permanents other than Worldslayer. ,Equip {5} ({5}: Attach to target creature you control. Equip only as a sorcery.) "],
    ["223"," Wurm's Tooth"," Artifact "," 2"," 2"," None"," Whenever a player casts a green spell, you may gain 1 life. "],
    ["224"," Buried Ruin"," Land "," 0"," 0"," None"," {T}: Add {1} to your mana pool. ,{2}, {T}, Sacrifice Buried Ruin: Return target artifact card from your graveyard to your hand. "],
    ["225"," Dragonskull Summit"," Land "," 0"," 0"," None"," Dragonskull Summit enters the battlefield tapped unless you control a Swamp or a Mountain. ,{T}: Add {B} or {R} to your mana pool. "],
    ["226"," Drowned Catacomb"," Land "," 0"," 0"," None"," Drowned Catacomb enters the battlefield tapped unless you control an Island or a Swamp. ,{T}: Add {U} or {B} to your mana pool. "],
    ["227"," Glacial Fortress"," Land "," 0"," 0"," None"," Glacial Fortress enters the battlefield tapped unless you control a Plains or an Island. ,{T}: Add {W} or {U} to your mana pool. "],
    ["228"," Rootbound Crag"," Land "," 0"," 0"," None"," Rootbound Crag enters the battlefield tapped unless you control a Mountain or a Forest. ,{T}: Add {R} or {G} to your mana pool. "],
    ["229"," Sunpetal Grove"," Land "," 0"," 0"," None"," Sunpetal Grove enters the battlefield tapped unless you control a Forest or a Plains. ,{T}: Add {G} or {W} to your mana pool. "],
    ["230"," Plains"," Basic Land - Plains "," 0"," 0"," None"," W "],
    ["231"," Plains"," Basic Land - Plains "," 0"," 0"," None"," W "],
    ["232"," Plains"," Basic Land - Plains "," 0"," 0"," None"," W "],
    ["233"," Plains"," Basic Land - Plains "," 0"," 0"," None"," W "],
    ["234"," Island"," Basic Land - Island "," 0"," 0"," None"," U "],
    ["235"," Island"," Basic Land - Island "," 0"," 0"," None"," U "],
    ["236"," Island"," Basic Land - Island "," 0"," 0"," None"," U "],
    ["237"," Island"," Basic Land - Island "," 0"," 0"," None"," U "],
    ["238"," Swamp"," Basic Land - Swamp "," 0"," 0"," None"," B "],
    ["239"," Swamp"," Basic Land - Swamp "," 0"," 0"," None"," B "],
    ["240"," Swamp"," Basic Land - Swamp "," 0"," 0"," None"," B "],
    ["241"," Swamp"," Basic Land - Swamp "," 0"," 0"," None"," B "],
    ["242"," Mountain"," Basic Land - Mountain "," 0"," 0"," None"," R "],
    ["243"," Mountain"," Basic Land - Mountain "," 0"," 0"," None"," R "],
    ["244"," Mountain"," Basic Land - Mountain "," 0"," 0"," None"," R "],
    ["245"," Mountain"," Basic Land - Mountain "," 0"," 0"," None"," R "],
    ["246"," Forest"," Basic Land - Forest "," 0"," 0"," None"," G "],
    ["247"," Forest"," Basic Land - Forest "," 0"," 0"," None"," G "],
    ["248"," Forest"," Basic Land - Forest "," 0"," 0"," None"," G "],
    ["249"," Forest"," Basic Land - Forest "," 0"," 0"," None"," G "]]

def random_pack():
    pack = []
    if random.randrange(8) == 0:
        pack.append(random.choice(mythic))
    else:
        pack.append(random.choice(rare))
    pack.extend(random.sample(uncommon,3))
    pack.extend(random.sample(common,10))
    pack.append(random.choice(land))
    return pack
